"""empty message

Revision ID: 134f67c9199f
Revises: 
Create Date: 2017-07-13 23:26:44.274527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134f67c9199f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tips', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tips', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tips', type_='foreignkey')
    op.drop_column('tips', 'author_id')
    # ### end Alembic commands ###
